### ISSUE TITLE
When hunting grids to restore, player.IdentityId is not obvious

### ISSUE THREAD

**Issue by mccorkle** [LordTylus/SE-Torch-Plugin-ALE-GridBackup#1]
Is it possible to make it optional for an admin to store grid backups into the player's (sanitize for disk safety) name instead of their IdentityId?

To sanitize the player name, something like the following: 
public string ReplaceInvalidChars(string filename)
{
    return string.Join("_", filename.Split(Path.GetInvalidFileNameChars()));    
}
(stolen from https://stackoverflow.com/questions/146134/how-to-remove-illegal-characters-from-path-and-filenames)

And if this were optional, I'd see some kind of check around lines 40 and 111 (where you use `player.IdentityId` in `Plugin.CreatePathForPlayer` to make the path).   

Not sure if you are accepting PRs, but if so, I'd be happy to submit this as one.

**Comment by LordTylus** [comment]
Hi,

Thank you for the suggestion. I originally decided against using the players name for grid backups. Since it happens from time to time that two players with the same name join the server which will give you a hard time dealing with the backups so identity or steam id made the most sense to me. 

Since NPC ships and stations of manually added npcs for scenariod etc don't have a steam id i ultimately decided against using steam id.

An other thing i tried to avoid by using the identity is that players can change their username which the game only partially supports. 

So far I at least never had the use case to manually look in the backups folder to restore a grid since the server itself can do that for me just fine but I can add an option for that tomorrow. As you said its relatively easy to implement.

Out of curiosity do you only want the player name or can it also be a combination of identity id and player name to tell to different players with same name apart?

I already use the replace function for the gridnames in the players folder.

Kind regards

**Comment by LordTylus** [comment]
Btw could you elaborate on why you "hunt" for grid in the folder structure instead of using the !gridbackup list and restore commands?

**Comment by mccorkle** [comment]
I totally get it -- and in the cases that I have multiple users with the same name (as steam doesn't enforce "friendly" name uniqueness) then I totally see why you want to use EntityID (also for entities like npcs too).  

My case is an edge case, I'm pretty sure.  

Something happened last night which broke the auto-save as well as Torch's ability to save during my scheduled restart (done via essentials).  

This left me with a full world auto-save from around around 9:50pm, but then nothing else until 7:20am -- with my auto-saves supposedly happening every 5 minutes and my restart happening at 04:00:00 (again, via Essentials 1.7.1.46-107)

When the server restarted at 4am, it was not able to save the working state of the game.  Torch exited, and upon reload, the last world save it found was 9:50pm from the night before.  As expected, it restarted with that save file from 9:50pm and continued on with its server duties.  

Normally, all I could have told my players in a case like this is:  "I'm sorry, I lost all your work" from last night. 

But in this case, GridBackup was doing its job, and we have successful grid backups for all of the grids that people worked on past the 9:50pm point.  

So knowing this, I got excited and I tried the restore through the `!gridbackup restore` -- but it yielded the grid from sometime around the 9:50pm backup -- as those are the grids that were live in the universe after the restart.  

So I tried to go back a few more steps and realized it wasn't consistent for the four players that I working on.  What was worse is that the players didn't always know exactly which version of their grid was the "right" one to restore.  

That is when I dove into the actual grids on the file system where I could see timestamps, grid names names, and sbc file sizes.  That is how I figured out -- "grab the last one right before 4am" or "grab the largest one" was the best case for my players.  

For my hardest to please player, I handed them a zip with all of the versions of their grid renamed to look like blueprints so that they could drop them into their %appdata%.  With that, they opened up creative and they were ale to find the version of their grid which they wanted me to restore.  

In both of these cases, looking at the folder via windows Explorer was super helpful -- but I first had to figure out who 144115188075855999 was and if that Identity_id was a user with a lost grid. 

Though it was pretty easy to dig into the sbs/sbc to cross reference ID to name, it wasn't intuitive and more time time and opportunity for human error. And that was only because I knew that EntityID, SteamID, and player name could be looked up in the sbs/sbc world save files.  

If I was going to modify the `!gridbackup` to support my edge case, I'd need to be able to see more details on each grid (pcu count, block count, or at least filesize) and I would have needed to easily see that data for multiple users (I had 4 in my case, but a more active server might have had more).  

I don't know how I could have supported the case where I just sent the user an export of all their grids & versions.  Unless there is a way for me to `!gridback give "user name" 44` and pop up the "blueprint" window for a user.  Don't know if any of that is exposed to you, but would have yielded the same where I could have just given the end user his grids and let him figure it out.  Then, if I was feeling really trusting, I could have promoted them up to copy/paste level live on the server for a moment and let him paste in the right one himself.  

re: if I could work with the {username}_{IdentityId} -- that would have been fine as well, as long as I could sort on the usernames to easily find my players which I was trying to restore.

**Comment by LordTylus** [comment]
Okay that sounds a bit weird but reasonable. Sadly I dont have things like PCU count at hand as i would need to load the actual sbc file to get these information. 

However i could maybe save them as metadata Next to the sbc file. I might look into that in the future.

For your use case i can build in an option tonight to get the playername_identityid result. However this will cause that the gridbackup cannot find the old backups as the locations have changed.

**Comment by mccorkle** [comment]
Thanks man.  Just close this issue when its ready to test and I'll pull your branch down and replace my "master" plugin with the branch for testing.

**Comment by LordTylus** [comment]
@mccorkle I built it in an Tested it. 

you can download the latest version from Torches Website
https://torchapi.net/plugins/item/75e99032-f0eb-4c0d-8710-999808ed970c

![image](https://user-images.githubusercontent.com/22499516/75370786-f0cd2800-58c5-11ea-98a1-81e208ae027d.png)

**Comment by mccorkle** [comment]
Brilliant!  Thank you sir!  I'll give it a test tonight.

**Comment by mccorkle** [comment]
Confirmed working with ALE Grid Backup v1.0.0.7 and torch v1.3.1.104-master.  

Thank you @LordTylus 👍
