### ISSUE TITLE
Is there a way for me to filter out backups of non-player characters identities?

### ISSUE THREAD

**Issue by mccorkle** [LordTylus/SE-Torch-Plugin-ALE-GridBackup#2]
Is there a way for me to filter out backups of non-player characters identities?

When looking through my Sandbox.sbc, the only immediately obvious thing I see to distinguish players and NPCs is that player's have a `/MyObjectBuilder_Checkpoint/Identities/MyObjectBuilder_Identity/Model` and npcs don't.  I'm sure there is a more graceful way to check that in memory though.

It looks like my "Space Pirate" identity ended up with 1,397 distinct folders (each with X backups per grid):
![image](https://user-images.githubusercontent.com/2091058/75612694-0aec4d80-5af4-11ea-84cf-383ffea0ed63.png)

**Comment by LordTylus** [comment]
NPC Identities have an NPC Flag to check at runtime. So they can be filtered. however you yourself cannot do that right now. 

I assume your next question will be if I can add an option to filter out NPCs and dont backup them which actually makes a whole lot of sense :-) 

Yes I could do that if thats what you need :-)

**Comment by mccorkle** [comment]
Lol, yep.  When a server is running a dynamic pve set of mods, we have a LOT of NPCs and even more grids spawned and despawned throughout the day, driving our backup storage need through the roof.

**Comment by LordTylus** [comment]
Will fix that tomorrow

**Comment by LordTylus** [comment]
Addid this feature to 1.0.0.8 have fun with it :-)

**Comment by mccorkle** [comment]
Dude, that is awesome.  Thank you so much!
