### ISSUE TITLE
Progressive Backup option

### ISSUE THREAD

**Issue by LostProger** [LordTylus/SE-Torch-Plugin-ALE-GridBackup#3]
Suggestion: Progressive Backup
Proposed way of how that works:
Let's say we have N maximum backups per grid. With this setting on, some number of those are usual backups done with usual period.

Hovewer, others follow that pattern:
M (less than N) backups have some hours (4-6) interval between them. When the new interval starts, the oldest "usual" backup becomes the most fresh in those - the backup of past period.
M (or M/2?) backups are daily. When the new day starts, the oldest hours-unterval backup becomes the most fresh among these - the backup of past day.
M (or M/4) are, say, weekly. When the new week starts, the oldest daily backup becomes the backup of past week.

That way, we still have total N backups per grid, but we gain access to older states too: hours, days, weeks ago, while still having the necessary amount of fresh backups.

**Comment by LordTylus** [comment]
I don't plan to add anything super fancy. We have the Number of Backups per interval which you can configure freely. And Now I also added the option to keep the first backup of the day for a configurable amount of days. 

By Default Daily Backups are disabled. To have access to daily backups you need at least Version 1.0.2.0 of the Gridbackup Plugin. 

![image](https://user-images.githubusercontent.com/22499516/79017739-61788d00-7b72-11ea-9737-3dd43a5fdb95.png)

If you set up a 30 Minute interval with the option to keep 5 Backups you have 2.5 hours worth of grid-backups. 
And if you also configure to save the first backup of the Day for 5 Days you have 5 Additional backups dating to 5 days back. 

Weekly Backups in a Space Engineers World sound overkill for me. 

I consider this Issue closed with it as of now I dont plan to add any more to it.
