### ISSUE TITLE
Feature request? Bug? Running "!gridbackup run" does not report back completion in logs

### ISSUE THREAD

**Issue by kontu** [LordTylus/SE-Torch-Plugin-ALE-GridBackup#5]
Unsure if this counts as a feature request or bug, I can edit as needed to reflect what you find / decide

Using automatic backup intervals within the Gridbackup plugin we see the following log output for it :
`01:16:27.8085 [INFO]   ALE_GridBackup.GridBackupPlugin: Start Backup process!
01:18:45.9190 [INFO]   ALE_GridBackup.GridBackupPlugin: Backup took 138107ms (1093ms CPU)
`

However if we use "!gridbackup run" in say an Essentials Autocommand; it does not report back how long the Backup took and we only see the following logged.

`07:07:25.9192 [INFO]   ALE_GridBackup.GridBackupPlugin: Start Backup process!
07:07:25.9192 [INFO]   Torch.Commands.CommandManager: Server ran command '!gridbackup run'
`

We've switched to using !gridbackup run as an autocommand because that way we can force a gridbackup before running our scheduled cleanup processes (because trying to juggle an interval scheduled cleanup with delays doesn't play nicely with other plugins automation); it'd be nice to be able to still validate in the logs how long a backup process is running for so we can be sure we aren't doing cleanup while backups are still running.

**Comment by LordTylus** [comment]
The logging is correct, however but as discussed over on discord taking manual backups with disabled interval was not working.

Well now it does. Fixed in v1.0.3.2
