### ISSUE TITLE
Feature request: Output IdentityID on Gridbackup list of player

### ISSUE THREAD

**Issue by kontu** [LordTylus/SE-Torch-Plugin-ALE-GridBackup#7]
Any chance you could add IdentityID of the player after the name in the output?
https://i.imgur.com/rsWUoYT.png

It would make it real easy for someone to manually find the folder of the player they need to look up (which also would mean being a workaround for the "use steamid" feature request)

**Comment by LordTylus** [comment]
Sure can do

**Comment by LordTylus** [comment]
Did so in 1.0.3.8
